name: DisVar
channels:
  - defaults
  - conda-forge
dependencies:
  - aom=3.6.0
  - asttokens=3.0.0
  - biopython=1.85
  - blas=1.0
  - bottleneck=1.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.12.1
  - dav1d=1.2.1
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.14.1
  - fribidi=1.0.10
  - gettext=0.21.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.11
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.5.2
  - jpeg=9f
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.84.4
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - munkres=1.1.4
  - ncurses=6.5
  - numexpr=2.11.0
  - numpy=2.3.4
  - numpy-base=2.3.4
  - openjpeg=2.5.3
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pixman=0.46.4
  - prompt-toolkit=3.0.52
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - qhull=2020.2
  - readline=8.3
  - requests=2.32.5
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - afrc==0.3.7
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - attrs==25.4.0
      - cython==3.1.6
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - getsequence==2.2.1
      - idptools-parrot==1.7.6+3.g0c2d4e4
      - jinja2==3.1.6
      - lightning-utilities==0.15.2
      - llphyscore==0.1
      - markupsafe==3.0.3
      - metapredict==3.0.1
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.5
      - pip==25.3
      - propcache==0.4.1
      - protfasta==0.1.15.2
      - pybind11==3.0.1
      - pyfamsa==0.6.1
      - pytorch-lightning==2.5.5
      - pyyaml==6.0.3
      - scoring-matrices==0.3.3
      - seaborn==0.13.2
      - sparrow==0.2.2+55.g2a9b8a0
      - sympy==1.14.0
      - torch==2.9.0
      - torchmetrics==1.8.2
      - yarl==1.22.0
prefix: /Users/Eytan/miniconda3/envs/DisVar
