name: DisVar
channels:
  - defaults
  - conda-forge
dependencies:
  - aom=3.6.0=h313beb8_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - biopython=1.85=py312h72d1ebd_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py312ha86b861_0
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - brotlicffi=1.0.9.2=py312h50f4ffc_2
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - certifi=2025.10.5=py312hca03da5_0
  - cffi=2.0.0=py312h73c2a22_1
  - charset-normalizer=3.4.4=py312hca03da5_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.1=py312h48ca7d4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=h80987f9_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.60.1=py312h254cc4a_0
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.10=h1a28f6b_0
  - gettext=0.21.0=hbdbcc25_2
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.1=h313beb8_0
  - idna=3.11=py312hca03da5_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9f=h2f69dba_0
  - kiwisolver=1.4.8=py312h313beb8_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=hd64df32_1
  - libavif=1.1.1=h80987f9_0
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcxx=20.1.8=h8869778_0
  - libdeflate=1.22=hd74edd7_0
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.16=h80987f9_3
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libopenblas=0.3.30=hf2bb037_0
  - libpng=1.6.50=h280e0eb_1
  - libtiff=4.7.0=h91aec0a_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=h4a912ad_3
  - matplotlib=3.10.6=py312hca03da5_0
  - matplotlib-base=3.10.6=py312h066045a_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - numexpr=2.11.0=py312h8c72970_1
  - numpy=2.3.4=py312hc95ac1c_0
  - numpy-base=2.3.4=py312h8087a70_0
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.5.4=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hc6ded6b_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h1dacb4a_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py312h6dd570d_0
  - pixman=0.46.4=h09dc60e_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py312hca03da5_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=py312hca03da5_1
  - python=3.12.12=h2bfc596_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py312hca03da5_0
  - scikit-learn=1.7.2=py312hc6ded6b_0
  - scipy=1.16.2=py312h53ebd84_0
  - setuptools=80.9.0=py312hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py312h80987f9_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py312hca03da5_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py312hca03da5_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - afrc==0.3.7
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - attrs==25.4.0
      - cython==3.1.6
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - getsequence==2.2.1
      - idptools-parrot==1.7.6+3.g0c2d4e4
      - jinja2==3.1.6
      - lightning-utilities==0.15.2
      - llphyscore==0.1
      - markupsafe==3.0.3
      - metapredict==3.0.1
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.5
      - pip==25.3
      - propcache==0.4.1
      - protfasta==0.1.15.2
      - pybind11==3.0.1
      - pyfamsa==0.6.1
      - pytorch-lightning==2.5.5
      - pyyaml==6.0.3
      - scoring-matrices==0.3.3
      - seaborn==0.13.2
      - sparrow==0.2.2+55.g2a9b8a0
      - sympy==1.14.0
      - torch==2.9.0
      - torchmetrics==1.8.2
      - yarl==1.22.0
prefix: /Users/Eytan/miniconda3/envs/DisVar
