name: DisVar
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - jupyter
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - biopython
  - tqdm
  - ipython
  - requests
  - pip
  - pip:
      - afrc==0.3.7
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - attrs==25.4.0
      - cython==3.1.6
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - getsequence==2.2.1
      - jinja2==3.1.6
      - lightning-utilities==0.15.2
      - markupsafe==3.0.3
      - metapredict==3.0.1
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.5
      - -r requirements.txt
      - propcache==0.4.1
      - protfasta==0.1.15.2
      - pybind11==3.0.1
      - pyfamsa==0.6.1
      - pytorch-lightning==2.5.5
      - pyyaml==6.0.3
      - scoring-matrices==0.3.3
      - seaborn==0.13.2
      - sympy==1.14.0
      - torch==2.9.0
      - torchmetrics==1.8.2
      - yarl==1.22.0